# Generated by Django 2.2.1 on 2019-05-15 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 34, 2, 970647)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='modifyTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 34, 2, 970647)),
        ),
    ]
