# Generated by Django 2.2.1 on 2019-05-15 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20190515_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 43, 53, 425064)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='modifyTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 43, 53, 425064)),
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
