# Generated by Django 2.2.1 on 2019-05-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
