# Generated by Django 2.2.1 on 2019-05-15 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20000)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 32, 7, 52714))),
            ],
        ),
    ]
