# Generated by Django 2.2.1 on 2019-05-15 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0002_posts_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Replys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='author',
            field=models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replys',
            name='fatherId',
            field=models.ForeignKey(null=True, on_delete='Cascade', to='Replys.Replys'),
        ),
        migrations.AddField(
            model_name='replys',
            name='postId',
            field=models.ForeignKey(on_delete='Cascade', to='Posts.Posts'),
        ),
    ]
