# Generated by Django 2.2.1 on 2019-05-15 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Replys', '0003_auto_20190515_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replys',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 43, 53, 428081)),
        ),
        migrations.AlterModelTable(
            name='replys',
            table='replys',
        ),
    ]
